### ISSUE TITLE
Make templates non-bindable

### ISSUE THREAD

**Issue by fabiand** [fabiand/v2v-job#10]
Today users can mark a vm as bindable in the v2v dialog when the service broker is used.

The template can expose a field to prevent this:

https://docs.openshift.com/container-platform/3.7/dev_guide/templates.html#writing-marking-templates-as-bindable

**Comment by pkliczewski** [comment]
@fabiand Do we want to ask user whether they want to make it bindable?

**Comment by fabiand** [comment]
Not at the moment, because we don't provide any object which is bindable (we'd need to provide a secret, volume, … which another service could use  - and we don't do this)

**Comment by fabiand** [comment]
Closed in favor of https://github.com/ansibleplaybookbundle/import-vm-apb
